### ISSUE TITLE
Style button to clear selection

### ISSUE THREAD

**Issue by bartaelterman** [LifeWatchINBO/bird-tracking#73]
[This button](https://github.com/LifeWatchINBO/bird-tracking/blob/new-map/explorer/index.html#L74) needs to be styled and positioned.

**Comment by peterdesmet** [comment]
Fixed in 92cd0d3d83b809a32ba9c2c3fd6af9b13e2e7002

Button is now combined with distance buttons, but is still distinct enough. JS functionality still works + buttons render nice on any screen width.

![screen shot 2015-05-19 at 13 35 46](https://cloud.githubusercontent.com/assets/600993/7701940/47b7511c-fe2c-11e4-9ae4-769136b97e66.png)
